apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      imagePullPolicy: Always
      args: ["--context=git://github.com/petregordan/kaniko-demo",
             "--destination=petregordandockerhub/devops-toolkit:1.0.0"]
      volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker
        - name: kaniko-context
          mountPath: /context
  restartPolicy: OnFailure
  volumes:
    - name: kaniko-secret
      secret:
        secretName: regcred
        items:
          - key: .dockerconfigjson
            path: config.json
    - name: kaniko-context
      hostPath: /tmp/kaniko_context